### PR TITLE
Added multipart upload, added optional encryption/decryption.

### PR DESCRIPTION
**Pull request by pkaleta**
### Summary
- Added new `multipart_upload` command with optional number of threads as well as chunk size arguments;
- Integrated `python-gnupg` package and added optional encryption/decryption of files using GnuPG's RSA algo implementation. 
- Added optional `--encrypt` and `--decrypt` flags for enabling and disabling encryption respectively. The `--encrypt` is available for upload commands, whereas `--decrypt` for retrieval;
- Cleaned up the code a bit;
- Updated `README.md` and added `.gitignore`;
### Testing

Sucessfully uploaded and downloaded multiple files with and without encryption using multipart as well as single chunk upload method. Files were of different sizes ranging from 1KB to 3GB.

### CODE REVIEW

**Comment by aspiers** [comment]
What's the latest on this?

**Comment by pkaleta** [comment]
No response from @basak for over a year now. Not sure if he's still maintaining this project. You can try using https://github.com/pkaleta/glacier-cli instead.

**Comment by basak** [comment]
Sorry, this is near impossible for me to review:

From my initial review: "I appreciate the refactoring, but it's really hard to review when intermingled in the middle of other commits. I've managed to review this OK and I appreciate your work, but it would be great if in the future you could submit a separate pull request for each feature you add, and perhaps one for any refactoring you want to do."

**Comment by aspiers** [comment]
I entirely sympathesise with @basak's position here - I'm sure this PR is full of many great improvements, but it's so huge that it seems to me like it would be a nightmare to review.  @pkaleta is there any chance you could break it into smaller more manageable chunks, please?

**Comment by basak** [comment]
I do apologise for taking so long to say this. That is my fault - I should have asked as soon as you (pkaleta) updated your request. When I first saw the update, I thought "OK, I'll try and take this and break it up, figure it out and commit what I can". But it was such a large task I didn't get to it and forgot all about it.

I'd really to get pull requests in small manageable pieces with mistakes/corrections rebased out. Like the Linux kernel does it - it's easiest to review that way.

**Comment by aspiers** [comment]
Hmm, I probably asked the wrong person here - @sakoht is there any chance you could break this into smaller more manageable chunks, please?

**Comment by sakoht** [comment]
Adam I'd love to but I've left the company that needed it, and don't have the bandwidth to jump back currently.  Piotr is there (before and after me), and is more familiar with the latest state of things, I believe.

We aimed to have the update be very thorough before submitting.  Down side is the size, sadly.

**Comment by aspiers** [comment]
Thanks a lot for the update @sakoht!

**Pull request closed without merging**
