### PR TITLE
check py version and use file.buffer when python3

### PR DESCRIPTION
**Pull request by cnjr2**
attempt at fixing issue #74

### CODE REVIEW

**Comment by basak** [comment]
Thank you for the patch!

I'm not sure about this fix though. I do specify `argparse.FileType('rb')` so it isn't clear to me why a str is appearing.

If you think this is the correct fix, please could you explain _why_ use of the `buffer` attribute is appropriate for Python 3 but not for Python 2?

**Comment by soxofaan** [comment]
> I'm not sure about this fix though. I do specify argparse.FileType('rb') so it isn't clear to me why a str is appearing.

see my comment in https://github.com/basak/glacier-cli/issues/74#issuecomment-605530828

**Comment by soxofaan** [comment]
FYI: I created an alternative solution without version sniffing: #77

**Comment by basak** [comment]
Thanks. I merged #77, but thank you also to @cnjr2 for finding the original workaround.

**Pull request closed without merging**
